"use strict";
exports.__esModule = true;
var message = 'Todays date is ';
var date = new Date();
console.log(message + date);
//console.log(date);
var x = 10;
var y = 20;
var sum;
var ttile = 'Typescript tutorial';
var isBeginner = true;
var total = 0;
var name = 'richie';
var sentence = "My name is " + name + "\nI am a developer trying to learn typescript";
console.log(sentence);
